# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(default='Type your project link', max_length=250),
        ),
    ]
